# Generated by Django 4.0.3 on 2022-03-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(default='000000', max_length=6)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('fullname', models.CharField(blank=True, max_length=200)),
                ('user_email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('password', models.CharField(default='12345678', max_length=10)),
                ('mobile', models.CharField(blank=True, max_length=25, unique=True)),
                ('its_manager', models.BooleanField(default=False)),
                ('its_supervisor', models.BooleanField(default=False)),
                ('its_housekeeping', models.BooleanField(default=False)),
            ],
        ),
    ]
