# Generated by Django 4.0.3 on 2022-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(default='000000', max_length=6, unique=True),
        ),
    ]
