# Generated by Django 4.0.3 on 2022-03-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0002_alter_employee_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_email',
            field=models.EmailField(blank=True, default='blank@blank.com', max_length=50),
        ),
    ]
