# Generated by Django 4.0.3 on 2022-03-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0003_alter_employee_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
